---
apiVersion: v1
kind: Service
metadata:
  name: kiali
  namespace: {{ .Values.observability.kiali.namespace }}
  labels:
    
    helm.sh/chart: kiali-server-2.12.0
    app: kiali
    app.kubernetes.io/name: kiali
    app.kubernetes.io/instance: kiali
    version: "v2.12.0"
    app.kubernetes.io/version: "v2.12.0"
    app.kubernetes.io/part-of: "kiali"
  annotations:
spec:
  type: {{ $.Values.observability.kiali.serviceType | default "ClusterIP" }}
  ports:
  - name: http
    appProtocol: http
    protocol: TCP
    port: 20001
  - name: http-metrics
    appProtocol: http
    protocol: TCP
    port: 9090
  selector:
    app.kubernetes.io/name: kiali
    app.kubernetes.io/instance: kiali