---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/version: v3.4.2
    helm.sh/chart: prometheus-27.23.0
    app.kubernetes.io/part-of: prometheus
  name: prometheus
  namespace: {{ .Values.observability.prometheus.namespace }}
spec:
  type: {{ $.Values.observability.prometheus.serviceType | default "ClusterIP" }}
  ports:
    - name: http
      port: 9090
      protocol: TCP
      targetPort: 9090
  selector:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/instance: prometheus
  sessionAffinity: None